### ISSUE TITLE
Standard Tastenkombinationen wie z.B. Ctrl+F werden "überschrieben"

### ISSUE THREAD

**Issue by fwaechter** [Kartoffeleintopf/BsWatch#2]
Die Tastenkombinationen sollten nicht mit Ctrl/Strg angesprochen werden. So kann man z.B. die Browsersuche nicht mit Ctrl+f öffnen, weil BsWatch diese Kombi als "zu Favoriten hinzufügen" benutzt. Daher am besten für Kombinationen von BsWatch einen anderen Key (oder eine zusätzliche Taste, wie z.B. Shift) verwenden.

**Comment by Kartoffeleintopf** [comment]
Es wurde so geändert das BsWatch keine Keyeingaben entgegennimmt wenn Shift oder Strg gedrückt wird.
